In [2]:
import pandas as pd

In [16]:
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
df = pd.read_csv(url)#, error_bad_lines=False)

In [50]:
country_list = ['USA', 'CAN', 'GBR', 'DEU','ESP','FRA','ITA',\
                'AUS','CHN','IND','JPN','KOR','ARG','BRA','COL',\
                'MEX','TUR','SAU','ZAF','PAK','SWE','CHE','BEL','NLD',\
               'CZE','POL','RUS','HUN','ROU']

columns_of_interest = ['iso_code','continent', 'location','date','total_cases',\
                       'new_cases','total_deaths','new_deaths','total_cases_per_million',\
                       'new_cases_per_million','total_deaths_per_million', 'new_deaths_per_million',\
                       'reproduction_rate','icu_patients', 'icu_patients_per_million', 'hosp_patients',\
                       'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million',\
                       'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'total_tests',\
                       'new_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'positive_rate',
                       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'new_vaccinations',\
                       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',\
                       'stringency_index', 'population','hospital_beds_per_thousand']

df2 = df[df['iso_code'].isin(country_list)]
df3 = df2.loc[:,columns_of_interest]
df3.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'total_deaths', 'new_deaths', 'total_cases_per_million',
       'new_cases_per_million', 'total_deaths_per_million',
       'new_deaths_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand', 'positive_rate',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
       'new_vaccinations', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'stringency_index', 'population', 'hospital_beds_per_thousand'],
      dtype='object')

In [30]:
mobility = pd.read_csv('https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv', low_memory=False)

In [43]:
country_name_list = df3.location.unique()

mobility2 = mobility[mobility['country_region'].isin(country_name_list)]

28
29

In [51]:
full_data = df3.merge(mobility2, how='left',left_on=['location','date'],right_on=['country_region','date'], suffixes=('_owid','_goog'))
full_data.fillna(0)

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,ARG,South America,Argentina,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARG,South America,Argentina,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ARG,South America,Argentina,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ARG,South America,Argentina,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARG,South America,Argentina,2020-01-05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
full_data = full_data[full_data.sub_region_1.isnull()]
full_data = full_data[full_data.metro_area.isnull()]

In [73]:
full_data = full_data.drop(['sub_region_1','sub_region_2','metro_area','iso_3166_2_code','census_fips_code'], axis = 1)

In [75]:
full_data.to_csv("./COVID_Module_Data.csv")